#!/bin/bash
spanFactor="360/5"
cutoffFraction="0.1" # Ignores the first cutoffFraction*totalLines timesteps.
timeFolder="0" # Where to look for forces file: postProcessing/forcesName/timeFolder/forces.dat

# Get total number of lines.
wcOut=(`wc -l postProcessing/total/$timeFolder/forces.dat`) # Get file size data
totalLines=${wcOut[0]} # Number of lines in forces.dat

# Get the starting line.
cutoffLine=$(echo "$cutoffFraction*$totalLines" | bc) # Calculate the cutoff using floating point.
cutoffLine=${cutoffLine%.*} # Truncates the decimal part.

# Make new files more amenable to plotting.
declare -a arr=(total rotor duct) # make array of forces folders.
cd postProcessing
for i in ${arr[@]} # iterate through array.
do
	cd $i/$timeFolder
	sed -n "$cutoffLine,\$p" < forces.dat > processed # Get last part of file
	sed -i "s/[(),]/ /g" processed # eliminate non-numeric characters and turn them into whitespace.
	cd ../../
done
cd ../

# If you replace all of the parentheses and commas with whitespace, you get:
# time	pressureForce(X Y Z) viscousForce(X Y Z) porousForce(X Y Z) pressureMoment(X Y Z) viscousMoment(X Y Z) porousMoment(X Y Z) 
# Time is column 1
# Z moment is columns 13,16 
# Y force is columns 3,6
# X force is columns 2,5 
ft="postProcessing/total"
fr="postProcessing/rotor"
fd="postProcessing/duct"
ff="$timeFolder/processed"
gnuplot -persist > /dev/null 2>&1 << EOF
	set key right center
	set title "Performance"
	set ylabel 'Performance Metric'
	set xlabel 'Time (s)'
	set term wxt

	f(x) = mean_total_thrust
	fit f(x) "$ft/$ff" u 1:((\$3+\$6)*$spanFactor) via mean_total_thrust
	f(x) = mean_duct_thrust
	fit f(x) "$fd/$ff" u 1:((\$3+\$6)*$spanFactor) via mean_duct_thrust
	f(x) = mean_rotor_thrust
        fit f(x) "$fr/$ff" u 1:((\$3+\$6)*$spanFactor) via mean_rotor_thrust
	set label 1 gprintf("Mean Total Thrust = %g N", mean_total_thrust) at graph 0.05, graph .55 
	set label 2 gprintf("Mean Duct Thrust = %g N", mean_duct_thrust) at graph 0.05, graph .5
	set label 3 gprintf("Mean Rotor Thrust = %g N", mean_rotor_thrust) at graph 0.05, graph .45

	plot	"$ft/$ff" u 1:((\$3+\$6)*$spanFactor) t 'Total Thrust (N)' with lines,\
		"$fd/$ff" u 1:((\$3+\$6)*$spanFactor) t 'Duct Thrust (N)' with lines,\
		"$fr/$ff" u 1:((\$3+\$6)*$spanFactor) t 'Rotor Thrust (N)' with lines
EOF
