#!/bin/bash
logfile="log"
string="p;N;N;N;"
gnuplot -persist << EOF
	set logscale y
	set title "Residuals"
	set ylabel 'Residual'
	set xlabel 'Iteration'
	plot "< cat $logfile | grep 'Solving for Ux' | cut -d' ' -f9 | tr -d ','" title 'Ux' with lines,\
		"< cat $logfile | grep 'Solving for Uy' | cut -d' ' -f9 | tr -d ','" title 'Uy' with lines,\
		"< cat $logfile | grep 'Solving for Uz' | cut -d' ' -f9 | tr -d ','" title 'Uz' with lines,\
		"< cat $logfile | grep 'Solving for p' | cut -d' ' -f9 | sed -n '$string' | tr -d ','" title 'p' with lines,\
		"< cat $logfile | grep 'Solving for nuTilda' | cut -d' ' -f9 | tr -d ','" title 'nuTilda' with lines
EOF
