#!/bin/bash

gnuplot -persist > /dev/null 2>&1 << EOF
	set title "Lift-to-Drag Ratio vs. Angle of Attack"
	set xlabel "Angle of Attack (Degrees)"
	set ylabel "Lift-To-Drag Ratio"
	plot	"first_arc_300" u 1:(\$2/\$3) t "arc 300" w linespoints,\
			"first_flatplate_300" u 1:(\$2/\$3) t "flatplate 300" w linespoints
			
EOF
