#!/bin/bash

gnuplot -persist > /dev/null 2>&1 << EOF
	set title "Lift, Drag, and Moment Coefficients vs. Angle of Attack"
	set xlabel "Angle of Attack (Degrees)"
	set ylabel "Lift, Drag, or Moment Coefficient"
	plot	"first_flatplate_75" u 1:2 t "CL 75" w linespoints,\
			"first_flatplate_75" u 1:3 t "CD 75" w linespoints,\
			"first_flatplate_75" u 1:4 t "CM 75" w linespoints,\
			"first_flatplate_150" u 1:2 t "CL 150" w linespoints,\
			"first_flatplate_150" u 1:3 t "CD 150" w linespoints,\
			"first_flatplate_150" u 1:4 t "CM 150" w linespoints,\
			"first_flatplate_300" u 1:2 t "CL 300" w linespoints,\
			"first_flatplate_300" u 1:3 t "CD 300" w linespoints,\
			"first_flatplate_300" u 1:4 t "CM 300" w linespoints
EOF
