#!/bin/bash

gnuplot -persist > /dev/null 2>&1 << EOF
	set title "Lift, Drag, and Moment Coefficients vs. Angle of Attack"
	set xlabel "Angle of Attack (Degrees)"
	set ylabel "Lift, Drag, or Moment Coefficient"
	plot	"first_multiarc_300" u 1:2 t "CL multiarc 300" w linespoints,\
			"first_multiarc_300" u 1:3 t "CD multiarc 300" w linespoints,\
			"first_multiarc_300" u 1:4 t "CM multiarc 300" w linespoints,\
			"first_arc_300" u 1:2 t "CL arc 300" w linespoints,\
			"first_arc_300" u 1:3 t "CD arc 300" w linespoints,\
			"first_arc_300" u 1:4 t "CM arc 300" w linespoints,\
			"first_flatplate_300" u 1:2 t "CL flatplate 300" w linespoints,\
			"first_flatplate_300" u 1:3 t "CD flatplate 300" w linespoints,\
			"first_flatplate_300" u 1:4 t "CM flatplate 300" w linespoints
EOF
